# Ollama本地模型配置
provider: "Ollama"
description: "Ollama本地部署模型"

models:
  language:
    - name: "llama3"
      display_name: "Llama 3"
      description: "Meta Llama 3 8B模型"
      
    - name: "llama3.1"
      display_name: "Llama 3.1"
      description: "Meta Llama 3.1 8B模型"
      
    - name: "mistral"
      display_name: "Mistral"
      description: "Mistral 7B模型"
      
    - name: "codellama"
      display_name: "CodeLlama"
      description: "CodeLlama代码生成模型"
      
  vision:
    - name: "llava"
      display_name: "LLaVA"
      description: "LLaVA视觉理解模型"
      
    - name: "llava-llama3"
      display_name: "LLaVA-Llama3"
      description: "基于Llama3的LLaVA视觉模型"