# OpenAI GPT模型配置
provider: "OpenAI"
description: "OpenAI GPT系列模型"

models:
  language:
    # GPT-5 系列模型
    - name: "gpt-5"
      display_name: "GPT-5"
      description: "OpenAI 最新旗舰模型，具备多模态能力，适用于编程、写作、健康等领域"

    - name: "gpt-5-mini"
      display_name: "GPT-5 Mini"
      description: "GPT-5 的轻量版，速度更快，适用于快速响应任务"

    - name: "gpt-5-pro"
      display_name: "GPT-5 Pro"
      description: "GPT-5 的专业版，适用于复杂推理和高质量输出"

  vision:
    - name: "gpt-5-image"
      display_name: "GPT-5 Image"
      description: "GPT-5 的图像处理模型，支持图像生成和理解"

  reasoning:
    - name: "gpt-5-thinking"
      display_name: "GPT-5 Thinking"
      description: "GPT-5 的推理模块，适用于需要深度思考的任务"

    - name: "o4-mini"
      display_name: "o4 Mini"
      description: "OpenAI 最新轻量级推理模型，适用于资源有限的环境"